http:
  "host": "0.0.0.0"
  "port": "8081"

https:
  "host": "localhost"
  "port": "8082"
    
moviesdb:
  "host": "bms.cdauio8pvb3a.us-east-2.rds.amazonaws.com"
  "port": "1433"
  "user": "admin"
  "password": "admin1234"
  "dbname": "MyDB"
  
file:
  TicketDR: "C:/studio-workspace/BMS-shalloo-nandini/Ticket"